# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - database.env
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - 5432:5432

  svdiris:
    image: svdiris
    ports: 
      - 8020:8020
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=sekret1
      - DJANGO_SUPERUSER_EMAIL=admin@example.com